name: train-my-model

on: 
  push:
    branches: [master]
  pull_request: 
    branches: [master]


jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-dvc@v1
      - name: Get data
        run: |
          dvc pull
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      - uses: iterative/setup-cml@v2
      - name: Train model
        run: |
          pip install -r requirements.txt  # install dependencies
          python BjarkeCCtemplate/train_cml.py  # run training
      - name: Write report
        env:
          # this authenticates that the right permissions are in place
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat classification_report.txt > report.md
          echo "![](./confusion_matrix.png)" >> report.md
          cml comment create --publish report.md